[tool.poetry]
name = "badk-official"
version = "0.1.0"
description = ""
authors = ["DaProWebStudio"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
django = "~5.2"
djangorestframework = "^3.18.1"
django-ckeditor = "^6.7.3"
django-cleanup = "^9.0.0"
django-debug-toolbar = "^8.0.0"
django-modeltranslation = "^0.20.6"
django-filter = "^26.1"
django-imagekit = "^6.1.1"
django-mptt = "^0.18.0"
transliterate = "^1.10.2"
environs = "^15.2.0"
pillow = "^12.3.0"
gunicorn = "^26.2.0"
whitenoise = "^6.8.2"
psycopg2-binary = "^2.9.13"
celery = "^5.6.3"
celery-singleton = "^0.3.1"
drf-yasg = "^1.21.15"
django-cachalot = "^2.9.1"
django-redis = "^7.0.0"
django-rosetta = "^0.10.3"
python-json-logger = "^4.2.0"
coverage = "^7.16.1"
djangorestframework-simplejwt = "^5.5.1"
django-cors-headers = "^4.9.0"
setuptools = "^84.0.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.test"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--tb=short",
    "--cov=apps",
    "--cov=common",
    "--cov=config",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-report=xml",
    "--cov-fail-under=70",
    "-v"
]
markers = [
    "slow: slow tests (integration)",
    "unit: unit tests",
    "integration: integration tests",
    "api: API tests",
    "models: model tests",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
