# Generated by Django 5.0 on 2026-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Unique identifier used in templates', unique=True)),
                ('value', models.TextField(blank=True)),
                ('value_ru', models.TextField(blank=True, null=True)),
                ('value_ky', models.TextField(blank=True, null=True)),
                ('value_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
