# Generated by Django 5.0 on 2026-02-03 06:30

import common.upload_to_files
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Национальность',
                'verbose_name_plural': 'Национальности',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('short_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название')),
                ('short_title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название')),
                ('short_title_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название')),
                ('short_title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=100, null=True, verbose_name='Порядковый номер')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('sur_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('men', 'Мужской'), ('women', 'Женский')], default='men', max_length=10, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='День рождения')),
                ('description', models.TextField(verbose_name='Резюме')),
                ('description_ru', models.TextField(null=True, verbose_name='Резюме')),
                ('description_ky', models.TextField(null=True, verbose_name='Резюме')),
                ('description_en', models.TextField(null=True, verbose_name='Резюме')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('work_skills', models.TextField(verbose_name='Навыки работы')),
                ('work_skills_ru', models.TextField(null=True, verbose_name='Навыки работы')),
                ('work_skills_ky', models.TextField(null=True, verbose_name='Навыки работы')),
                ('work_skills_en', models.TextField(null=True, verbose_name='Навыки работы')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.employee_file, verbose_name='Фото сотрудника')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.nationality', verbose_name='Национальность')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume', to='employee.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ('number',),
            },
        ),
    ]
