# Generated by Django 5.0 on 2026-02-03 06:30

import common.upload_to_files
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=100, null=True, verbose_name='Порядковый номер')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('sur_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('men', 'Мужской'), ('women', 'Женский')], default='men', max_length=10, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='День рождения')),
                ('description', models.TextField(verbose_name='Резюме')),
                ('description_ru', models.TextField(null=True, verbose_name='Резюме')),
                ('description_ky', models.TextField(null=True, verbose_name='Резюме')),
                ('description_en', models.TextField(null=True, verbose_name='Резюме')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.student_file, verbose_name='Фото студента')),
            ],
            options={
                'verbose_name': 'Студентский совет',
                'verbose_name_plural': 'Студентский совет',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='StudentLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.student_live, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Студентская жизнь',
                'verbose_name_plural': 'Студентская жизнь',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='StudentLiveImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.student_live_images, verbose_name='Фотография')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='student.studentlive')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('created',),
            },
        ),
    ]
